name: fission-web-server
version: '2.14.1.0'
category: API
author:
  - Brooklyn Zelenka
  - Daniel Holmgren
  - Steven Vandevelde
  - James Walker
  - Brian Ginsburg
  - Philipp Krüger
maintainer:
  - brooklyn@fission.codes
  - daniel@fission.codes
  - steven@fission.codes
  - james@fission.codes
  - brian@fission.codes
  - philipp@fission.codes
copyright: © 2021 Fission Internet Software Services for Open Networks Inc.
license: AGPL-3.0-or-later
license-file: LICENSE
github: fission-suite/fission
tested-with: GHC==8.10.4
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  # Warn about too little
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  # Warn about too much
  - -Wredundant-constraints
  # Prettier Development
  - -fhide-source-paths

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NumericUnderscores
  - OverloadedStrings
  - OverloadedLabels
  - OverloadedLists
  - PostfixOperators
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - TypeOperators
  - ViewPatterns

dependencies:
  ## Base ##
  - base
  - flow
  - rio
  - rio-orphans

  ## Capabilties ##
  - data-has
  - monad-logger
  - monad-time
  - mtl
  - resource-pool
  - streamly

  ## Concurrency ##
  - stm

  ## Cryptography ##
  - bcrypt
  - cryptonite

  ## Data ##
  - aeson
  - aeson-casing
  - base64-bytestring
  - bytestring
  - case-insensitive
  - generic-lens
  - lens
  - lens-aeson
  - QuickCheck
  - quickcheck-instances
  - random
  - text
  - time
  - uuid
  - vector
  - yaml

  ## Database ##
  - esqueleto
  - persistent
  - persistent-postgresql
  - persistent-template

  ## Error Handling ##
  - exceptions
  - rescue

  ## Fission
  - fission-core
  - fission-web-api

  ## File System ##
  - file-embed
  - path-pieces

  ## Formatting ##
  - pretty-simple

  ## Infrastructure ##
  - amazonka
  - amazonka-core
  - amazonka-route53
  - hostname

  ## Web ##
  - http-client
  - http-client-tls
  - http-media
  - http-types
  - ipfs
  - raven-haskell
  - servant
  - servant-auth-server
  - servant-auth-swagger
  - servant-client
  - servant-client-core
  - servant-server
  - servant-swagger
  - servant-swagger-ui-redoc
  - servant-websockets
  - swagger2
  - wai
  - wai-cors
  - wai-extra
  - wai-logger
  - warp
  - warp-tls
  - websockets

library:
  source-dirs: library

executables:
  fission-server:
    main: Main.hs
    source-dirs: server
    dependencies:
      - fission-core
      - fission-web-server
      - raven-haskell
      - wai-logger
    ghc-options:
      - -threaded
      - -flate-specialise
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T
      - -optc-ffast-math
      - -optc-O3
      - -O2

tests:
  fission-web-server-test:
    main: Main.hs
    source-dirs:
      - library
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - hspec-core
      - hspec-expectations
      - hspec-wai
      - hspec-wai-json
      - fission-web-server
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-hspec
      - tasty-smallcheck
      - tasty-rerun
      - transformers
      - world-peace

benchmarks:
  fission-web-server-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-A32m
      - -O2
    dependencies:
      - tasty-bench
      - fission-core
      - fission-web-server
